name: docs

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
        source_dir: docs

